version: '3'
services:
  db:
    build: ./db/
    environment:
      MYSQL_DATABASE: pet
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/docker-entrypoint-initdb.d/
  web:
    build: ./app/
    ports:
      - '5000:5000'
    depends_on:
      - db
    links:
      - 'db' 
